linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false # Allow blank identifier for intentional ignores
  govet:
    enable-all: true
    disable:
      - fieldalignment # Performance optimization, not critical
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam # TUI structs can be large

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m
  tests: true
