linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused
    - gosimple
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false # Allow blank identifier for intentional ignores
    # Exclude functions where errors are safe to ignore (TUI output, cleanup)
    exclude-functions:
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (*github.com/jroimartin/gocui.Gui).SetCurrentView
      - (*github.com/jroimartin/gocui.Gui).DeleteView
      - (*github.com/jroimartin/gocui.View).SetCursor
      - (github.com/jroimartin/gocui.Gui).SetCurrentView
      - (github.com/jroimartin/gocui.Gui).DeleteView
      - (github.com/jroimartin/gocui.View).SetCursor
      - (*os/exec.Cmd).Wait
      - os.Remove
      - (*golang.org/x/term).Restore
      - (golang.org/x/term).Restore
      - (*os.File).Close
      - (io.Closer).Close
  govet:
    enable-all: true
    disable:
      - fieldalignment # Performance optimization, not critical
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam # TUI structs can be large
      - octalLiteral # 0644 is more readable than 0o644 for file permissions
      - ifElseChain # Sometimes if-else is clearer than switch
      - paramTypeCombine # Explicit types can be more readable
      - commentedOutCode # Allow commented code for reference
      - appendAssign # False positive in some patterns

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10

run:
  timeout: 5m
  tests: true
