# Goreleaser config for GitHub Releases and Homebrew.
# Run: goreleaser release --snapshot  (dry run) or goreleaser release (with tag)
version: 2
project_name: lazykamal

before:
  hooks:
    - go mod tidy

builds:
  - id: lazykamal
    main: .
    binary: lazykamal
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -s -w -X main.version={{.Version }}
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "lazykamal_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - lazykamal

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  disable: true

release:
  github:
    owner: shuvro
    name: lazykamal
  draft: false

brews:
  - name: lazykamal
    repository:
      owner: shuvro
      name: homebrew-lazykamal
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/shuvro/lazykamal"
    description: "Lazydocker-style TUI for Kamal-deployed apps"
    license: "MIT"
    skip_upload: auto
    install: |
      bin.install "lazykamal"
    test: |
      system "#{bin}/lazykamal", "--version"

scoops:
  - name: lazykamal
    repository:
      owner: shuvro
      name: scoop-lazykamal
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/shuvro/lazykamal"
    description: "Lazydocker-style TUI for Kamal-deployed apps"
    license: MIT
    skip_upload: auto
